### ISSUE TITLE
Is x264 in this build 8bit or 10bit?

### ISSUE THREAD

**Issue by axfelix** [illuspas/ffmpeg-hw-win32#6]
Hi,

This ffmpeg build is really convenient, I'm very grateful to you for maintaining it. I wanted to ask whether x264 (the software encoder) in this ffmpeg is compiled for 8bit or 10bit since I understand that's configured at build time. I'm trying to transcode some HEVC video to h264 and still retain 10bit HDR colour.

Thanks!

**Comment by illuspas** [comment]
I use the upstream package mingw-w64-x264-git.
It uses the default configuration, bit depth:     8.  
If you like, you can compile ffmpeg yourself.
msys2 is my compile environment.

**Comment by axfelix** [comment]
OK, thanks -- I try to avoid compiling on Windows when I can, so I'll have to get over that :) Thanks for the quick response!
