### ISSUE TITLE
libnpp

### ISSUE THREAD

**Issue by sirber** [illuspas/ffmpeg-hw-win32#7]
Hi,

Could you please add libnpp? It allows for hardware scaling while using full hardware transcoding:

ffmpeg -hwaccel_device 0 -hwaccel cuvid -c:v h264_cuvid -i input -vf scale_npp=-1:720 -c:v h264_nvenc -preset slow output.mkv

Thank you!

**Comment by illuspas** [comment]
OK，give it a try. 17dc4b87e9d30d08af505ab59da0675cf568b518

**Comment by sirber** [comment]
Will try asap and will post results! Thank you!

**Comment by sirber** [comment]
ffmpeg.exe - System Error
---------------------------
The code execution cannot proceed because nppi64_80.dll was not found. Reinstalling the program may fix this problem.

**Comment by sirber** [comment]
the DLL is asked even for software encoding. might be good to add CUDA runtime to the requirements.

**Comment by sirber** [comment]
The DLL is here: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nppi64_80.dll
but ffmpeg doesn't seem to find it. did you do something special?

**Comment by sirber** [comment]
it works if I copy nppc64_80.dll and nppi64_80.dll (120MB) in the same folder ffmpeg.exe is. currently encoding with scale_npp! 👍

**Comment by illuspas** [comment]
When I compile and test, cuda sdk is in my system environment variable, I forget to check depend on it 😭 . This can be added to the bin directory, but the nppi64_80.dll file is sooo big

**Comment by sirber** [comment]
Do you mean the PATH variable? It works for DLLs too, and not just EXE?

**Comment by illuspas** [comment]
Yes.After installing CUDA, it will automatically add the directory to the system PATH environment variable, need to restart to take effect. Of course, copy dll to the directory same of ffmpeg.exe  can work without installing CUDA, but the file size exceeds github 100M limit.

**Comment by sirber** [comment]
God to know, thank you! In a 7z it's ~45MB, not too bad.
I think we can close this ticket, since it's working.

Thank you again! I'll link your repo when I release a new GUI version.
